# Generated by Django 3.2.5 on 2023-03-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('Truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('Truck_brand', models.CharField(max_length=100)),
                ('Truck_model', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('Driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('Driver_name', models.CharField(max_length=100)),
                ('Mobile_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('Language', models.CharField(blank=True, max_length=100, null=True)),
                ('Truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Driver.truck')),
            ],
        ),
    ]
